### ISSUE TITLE
PG Website Updating (Logo and Job Application Form)

### ISSUE THREAD

**Issue by cherrielam** [PeaceGeeksSociety/Core-Team#74]
Work with Tucker/Ron to figure out SASS to update CSS
Working with Magdi to link Job Application Form to SF

**Comment by cherrielam** [comment]
Emailed Ron to follow up about updating the Job Application Form

**Comment by andrewseong** [comment]
Issue moved to [PeaceGeeksSociety/peacegeeks-website #141](https://github.com/PeaceGeeksSociety/peacegeeks-website/issues/141) via [**ZenHub**](https://www.zenhub.com/)
